### ISSUE TITLE
Debug statements in the code

### ISSUE THREAD

**Issue by shytikov** [durgaprasadkatari/TagControl.PCF#1]
Unfortunately control didn't worked for me (I have no idea why), but when I tried to figure out if is there any errors in JS console it actually stopped on `debugger` statement.

I believe code packaged to solution was not fully production ready.

Could you please verify that managed solution will deliver working control?

**Comment by durgaprasadkatari** [comment]
Hi @shytikov ,
Thanks for catching the issue. I've removed the debuggers and updated the latest solutions. Please check let me know if you face any issues.

**Comment by durgaprasadkatari** [comment]
@shytikov Can you pls close this issue if it is resolved?
