### ISSUE TITLE
Tag questions

### ISSUE THREAD

**Issue by popujol** [durgaprasadkatari/TagControl.PCF#18]
Hello ,
Could you please advise if your PCF supports the following:
A tag can be created on the gow, not only taken from an existing values
A tag can be made of multiple words "Dynamics Customer Service" or "Power BI"
A tag can be suggested from an existing list
thank you!

Pierre-Olivier

**Comment by durgaprasadkatari** [comment]
Hello,
Apologies for the delayed response. I was on annual leave. Please find my response below.

- Tags can be created on the grow, it won't take from existing values.
- Tags can be made of multiple words. It supports "Dynamics 365 Customer Service"
- Tags cannot be suggested from the existing list.

Thanks,
Durgaprasad.

**Comment by popujol** [comment]
Hello Durgaprasad,
Many thanks for you answer.
Are you planning an evolution to enable new tags to feed a list of tags, and existing tag (used on other records) could be suggeste as the suer types? Like a "live" mutliselect option-set.
Thank you very much.

Kr,
Pierre-Olivier

**Comment by durgaprasadkatari** [comment]
Hello,

I don't have any plans to enable new tags to feed a list of tags. I think there is already a PCF control https://github.com/opc-cpvp/OPC.PowerApps.PCFControls that does this.
Also please have a look at the PCF.gallery website.

Thanks,
Durgaprasad.
