### ISSUE TITLE
Not working for Text Area / Multinline Text field

### ISSUE THREAD

**Issue by thatapiguy** [durgaprasadkatari/TagControl.PCF#8]
I tried using this for a text area / multiline text field and the tags control didn't show up in the list of custom controls.
Worked great for text field.

Thank you for creating this PCF. Very helpful!

**Comment by durgaprasadkatari** [comment]
I will look into it. Thanks for using this PCF.

Thanks,
Durgaprasad

**Comment by durgaprasadkatari** [comment]
Fixed this issue in the latest release #release 1.1
